//! Flow Summaries (Models as Data)
//!
//! This module provides declarative function summaries for tracking data flow
//! through library functions without source code, inspired by CodeQL's MaD format.
//!
//! Key concepts:
//! - SummarizedCallable: A function with known flow behavior
//! - FlowPropagation: How data flows from inputs to outputs
//! - SummaryComponent: Input/output specification (Argument[0], ReturnValue, etc.)
//!
//! Flow summaries enable precise analysis of library code like:
//! - `String.concat(x)` propagates taint from x to return value
//! - `StringBuilder.append(x)` propagates taint from x to this
//! - `StringEscapeUtils.escapeHtml(x)` sanitizes x for HTML context

use crate::content::Content;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fmt;

/// Provenance of a flow summary - where it came from
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Provenance {
    /// Manually written by security engineers
    Manual,
    /// Auto-generated from code analysis
    Generated,
    /// Generated by AI/ML
    AI,
    /// From external model file
    External(String),
}

impl Default for Provenance {
    fn default() -> Self {
        Provenance::Manual
    }
}

/// The kind of flow propagation
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum FlowKind {
    /// Value-preserving flow (exact data flows through)
    Value,
    /// Taint-propagating flow (derived data may be tainted)
    Taint,
    /// Sanitizing flow (removes taint for specific contexts)
    Sanitize(Vec<String>), // List of contexts sanitized (e.g., ["html", "sql"])
}

impl Default for FlowKind {
    fn default() -> Self {
        FlowKind::Taint
    }
}

/// A component in a summary specification
///
/// Components specify where data flows from/to in a function call.
/// Examples:
/// - `Argument[0]` - first argument
/// - `Argument[this]` - the receiver object
/// - `ReturnValue` - the return value
/// - `Argument[0].Field[data]` - field of first argument
/// - `CallbackParam[0, 0]` - first parameter of callback at argument 0
/// - `CallbackReturn[0]` - return value of callback at argument 0
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SummaryComponent {
    /// Function argument at position
    Argument(ArgumentSpec),
    /// Function return value
    ReturnValue,
    /// Nested content access
    Content {
        base: Box<SummaryComponent>,
        content: Content,
    },
    /// Parameter of a callback function passed as an argument
    /// (callback_arg_index, param_index) - the param_index-th parameter of the callback at callback_arg_index
    CallbackParam {
        callback_arg: usize,
        param_index: usize,
    },
    /// Return value of a callback function passed as an argument
    CallbackReturn {
        callback_arg: usize,
    },
}

/// Specification for an argument
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ArgumentSpec {
    /// Positional argument by index
    Index(usize),
    /// Named argument
    Named(String),
    /// The receiver (this/self)
    This,
    /// Any argument
    Any,
}

impl SummaryComponent {
    /// Create an argument component for position i
    pub fn argument(i: usize) -> Self {
        SummaryComponent::Argument(ArgumentSpec::Index(i))
    }

    /// Create the "this" argument component
    pub fn this() -> Self {
        SummaryComponent::Argument(ArgumentSpec::This)
    }

    /// Create a return value component
    pub fn return_value() -> Self {
        SummaryComponent::ReturnValue
    }

    /// Create a callback parameter component
    /// callback_arg: which argument is the callback (0-indexed)
    /// param_index: which parameter of the callback (0-indexed)
    pub fn callback_param(callback_arg: usize, param_index: usize) -> Self {
        SummaryComponent::CallbackParam {
            callback_arg,
            param_index,
        }
    }

    /// Create a callback return value component
    /// callback_arg: which argument is the callback (0-indexed)
    pub fn callback_return(callback_arg: usize) -> Self {
        SummaryComponent::CallbackReturn { callback_arg }
    }

    /// Create a content access on this component
    pub fn with_content(self, content: Content) -> Self {
        SummaryComponent::Content {
            base: Box::new(self),
            content,
        }
    }

    /// Create a field access on this component
    pub fn field(self, name: impl Into<String>) -> Self {
        self.with_content(Content::field(name))
    }

    /// Create an array element access on this component
    pub fn element(self) -> Self {
        self.with_content(Content::array_any())
    }

    /// Check if this component involves a callback
    pub fn involves_callback(&self) -> bool {
        match self {
            SummaryComponent::CallbackParam { .. } | SummaryComponent::CallbackReturn { .. } => true,
            SummaryComponent::Content { base, .. } => base.involves_callback(),
            _ => false,
        }
    }
}

impl fmt::Display for SummaryComponent {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SummaryComponent::Argument(spec) => match spec {
                ArgumentSpec::Index(i) => write!(f, "Argument[{}]", i),
                ArgumentSpec::Named(n) => write!(f, "Argument[{}]", n),
                ArgumentSpec::This => write!(f, "Argument[this]"),
                ArgumentSpec::Any => write!(f, "Argument[*]"),
            },
            SummaryComponent::ReturnValue => write!(f, "ReturnValue"),
            SummaryComponent::Content { base, content } => {
                write!(f, "{}.{}", base, content)
            }
            SummaryComponent::CallbackParam { callback_arg, param_index } => {
                write!(f, "CallbackParam[{}, {}]", callback_arg, param_index)
            }
            SummaryComponent::CallbackReturn { callback_arg } => {
                write!(f, "CallbackReturn[{}]", callback_arg)
            }
        }
    }
}

/// Describes how data flows through a function
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FlowPropagation {
    /// Where data flows from
    pub input: SummaryComponent,
    /// Where data flows to
    pub output: SummaryComponent,
    /// Kind of flow (value/taint/sanitize)
    pub kind: FlowKind,
    /// Provenance of this propagation rule
    #[serde(default)]
    pub provenance: Provenance,
}

impl FlowPropagation {
    /// Create a new taint propagation
    pub fn taint(input: SummaryComponent, output: SummaryComponent) -> Self {
        Self {
            input,
            output,
            kind: FlowKind::Taint,
            provenance: Provenance::default(),
        }
    }

    /// Create a value-preserving propagation
    pub fn value(input: SummaryComponent, output: SummaryComponent) -> Self {
        Self {
            input,
            output,
            kind: FlowKind::Value,
            provenance: Provenance::default(),
        }
    }

    /// Create a sanitizing propagation
    pub fn sanitize(input: SummaryComponent, output: SummaryComponent, contexts: Vec<String>) -> Self {
        Self {
            input,
            output,
            kind: FlowKind::Sanitize(contexts),
            provenance: Provenance::default(),
        }
    }

    /// Set the provenance
    pub fn with_provenance(mut self, provenance: Provenance) -> Self {
        self.provenance = provenance;
        self
    }
}

/// A callable (function/method) with known flow behavior
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SummarizedCallable {
    /// Unique signature (e.g., "java.lang.String.concat")
    pub signature: String,
    /// Package/namespace
    pub package: Option<String>,
    /// Class name (if method)
    pub class: Option<String>,
    /// Method/function name
    pub name: String,
    /// Flow propagation rules
    pub propagations: Vec<FlowPropagation>,
    /// Is this a source of tainted data?
    pub is_source: bool,
    /// Is this a sink for security vulnerabilities?
    pub is_sink: Option<String>, // Sink kind (e.g., "sql", "xss")
    /// Is this a sanitizer?
    pub is_sanitizer: bool,
    /// What contexts does it sanitize?
    pub sanitizes_for: Vec<String>,
}

impl SummarizedCallable {
    /// Create a new summarized callable
    pub fn new(signature: impl Into<String>, name: impl Into<String>) -> Self {
        Self {
            signature: signature.into(),
            package: None,
            class: None,
            name: name.into(),
            propagations: Vec::new(),
            is_source: false,
            is_sink: None,
            is_sanitizer: false,
            sanitizes_for: Vec::new(),
        }
    }

    /// Set package
    pub fn in_package(mut self, package: impl Into<String>) -> Self {
        self.package = Some(package.into());
        self
    }

    /// Set class
    pub fn in_class(mut self, class: impl Into<String>) -> Self {
        self.class = Some(class.into());
        self
    }

    /// Add a flow propagation
    pub fn with_propagation(mut self, prop: FlowPropagation) -> Self {
        self.propagations.push(prop);
        self
    }

    /// Mark as a taint source
    pub fn as_source(mut self) -> Self {
        self.is_source = true;
        self
    }

    /// Mark as a sink
    pub fn as_sink(mut self, kind: impl Into<String>) -> Self {
        self.is_sink = Some(kind.into());
        self
    }

    /// Mark as a sanitizer
    pub fn as_sanitizer(mut self, contexts: Vec<String>) -> Self {
        self.is_sanitizer = true;
        self.sanitizes_for = contexts;
        self
    }

    /// Check if this callable matches a given name
    pub fn matches(&self, name: &str) -> bool {
        // Check full signature
        if self.signature == name {
            return true;
        }
        // Check just the method name
        if self.name == name {
            return true;
        }
        // Check class.method
        if let Some(ref class) = self.class {
            let class_method = format!("{}.{}", class, self.name);
            if class_method == name {
                return true;
            }
        }
        // Check package.class.method
        if let (Some(ref pkg), Some(ref class)) = (&self.package, &self.class) {
            let full_name = format!("{}.{}.{}", pkg, class, self.name);
            if full_name == name {
                return true;
            }
        }
        false
    }
}

/// Registry of flow summaries
#[derive(Debug, Clone, Default)]
pub struct FlowSummaryRegistry {
    /// All registered summaries
    summaries: Vec<SummarizedCallable>,
    /// Index by name for fast lookup
    by_name: HashMap<String, usize>,
}

impl FlowSummaryRegistry {
    /// Create an empty registry
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a summary
    pub fn register(&mut self, summary: SummarizedCallable) {
        let idx = self.summaries.len();
        self.by_name.insert(summary.signature.clone(), idx);
        self.by_name.insert(summary.name.clone(), idx);
        if let Some(ref class) = summary.class {
            self.by_name.insert(format!("{}.{}", class, summary.name), idx);
        }
        self.summaries.push(summary);
    }

    /// Look up a summary by name
    pub fn get(&self, name: &str) -> Option<&SummarizedCallable> {
        self.by_name.get(name).map(|&idx| &self.summaries[idx])
    }

    /// Get all summaries
    pub fn all(&self) -> &[SummarizedCallable] {
        &self.summaries
    }

    /// Get all source functions
    pub fn sources(&self) -> impl Iterator<Item = &SummarizedCallable> {
        self.summaries.iter().filter(|s| s.is_source)
    }

    /// Get all sink functions
    pub fn sinks(&self) -> impl Iterator<Item = &SummarizedCallable> {
        self.summaries.iter().filter(|s| s.is_sink.is_some())
    }

    /// Get all sanitizer functions
    pub fn sanitizers(&self) -> impl Iterator<Item = &SummarizedCallable> {
        self.summaries.iter().filter(|s| s.is_sanitizer)
    }

    /// Create a registry with Java standard library summaries
    pub fn java_stdlib() -> Self {
        let mut registry = Self::new();

        // String operations
        registry.register(
            SummarizedCallable::new("java.lang.String.concat", "concat")
                .in_package("java.lang")
                .in_class("String")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(0),
                    SummaryComponent::return_value(),
                ))
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this(),
                    SummaryComponent::return_value(),
                )),
        );

        registry.register(
            SummarizedCallable::new("java.lang.String.substring", "substring")
                .in_package("java.lang")
                .in_class("String")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this(),
                    SummaryComponent::return_value(),
                )),
        );

        // StringBuilder operations
        registry.register(
            SummarizedCallable::new("java.lang.StringBuilder.append", "append")
                .in_package("java.lang")
                .in_class("StringBuilder")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(0),
                    SummaryComponent::this(),
                ))
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(0),
                    SummaryComponent::return_value(),
                )),
        );

        registry.register(
            SummarizedCallable::new("java.lang.StringBuilder.toString", "toString")
                .in_package("java.lang")
                .in_class("StringBuilder")
                .with_propagation(FlowPropagation::value(
                    SummaryComponent::this(),
                    SummaryComponent::return_value(),
                )),
        );

        // URLDecoder - propagates taint
        registry.register(
            SummarizedCallable::new("java.net.URLDecoder.decode", "decode")
                .in_package("java.net")
                .in_class("URLDecoder")
                .with_propagation(FlowPropagation::value(
                    SummaryComponent::argument(0),
                    SummaryComponent::return_value(),
                )),
        );

        // StringEscapeUtils - sanitizers
        registry.register(
            SummarizedCallable::new("org.apache.commons.lang.StringEscapeUtils.escapeHtml", "escapeHtml")
                .in_package("org.apache.commons.lang")
                .in_class("StringEscapeUtils")
                .with_propagation(FlowPropagation::sanitize(
                    SummaryComponent::argument(0),
                    SummaryComponent::return_value(),
                    vec!["html".to_string(), "xss".to_string()],
                ))
                .as_sanitizer(vec!["html".to_string(), "xss".to_string()]),
        );

        registry.register(
            SummarizedCallable::new("org.apache.commons.lang.StringEscapeUtils.escapeSql", "escapeSql")
                .in_package("org.apache.commons.lang")
                .in_class("StringEscapeUtils")
                .with_propagation(FlowPropagation::sanitize(
                    SummaryComponent::argument(0),
                    SummaryComponent::return_value(),
                    vec!["sql".to_string()],
                ))
                .as_sanitizer(vec!["sql".to_string()]),
        );

        // ESAPI sanitizers
        registry.register(
            SummarizedCallable::new("org.owasp.esapi.Encoder.encodeForHTML", "encodeForHTML")
                .in_package("org.owasp.esapi")
                .in_class("Encoder")
                .with_propagation(FlowPropagation::sanitize(
                    SummaryComponent::argument(0),
                    SummaryComponent::return_value(),
                    vec!["html".to_string(), "xss".to_string()],
                ))
                .as_sanitizer(vec!["html".to_string(), "xss".to_string()]),
        );

        registry.register(
            SummarizedCallable::new("org.owasp.esapi.Encoder.encodeForSQL", "encodeForSQL")
                .in_package("org.owasp.esapi")
                .in_class("Encoder")
                .with_propagation(FlowPropagation::sanitize(
                    SummaryComponent::argument(1), // First arg is codec
                    SummaryComponent::return_value(),
                    vec!["sql".to_string()],
                ))
                .as_sanitizer(vec!["sql".to_string()]),
        );

        // Servlet sources
        registry.register(
            SummarizedCallable::new("javax.servlet.http.HttpServletRequest.getParameter", "getParameter")
                .in_package("javax.servlet.http")
                .in_class("HttpServletRequest")
                .as_source(),
        );

        registry.register(
            SummarizedCallable::new("javax.servlet.http.HttpServletRequest.getQueryString", "getQueryString")
                .in_package("javax.servlet.http")
                .in_class("HttpServletRequest")
                .as_source(),
        );

        registry.register(
            SummarizedCallable::new("javax.servlet.http.Cookie.getValue", "getValue")
                .in_package("javax.servlet.http")
                .in_class("Cookie")
                .as_source(),
        );

        registry.register(
            SummarizedCallable::new("javax.servlet.http.HttpServletRequest.getHeader", "getHeader")
                .in_package("javax.servlet.http")
                .in_class("HttpServletRequest")
                .as_source(),
        );

        registry.register(
            SummarizedCallable::new("javax.servlet.http.HttpServletRequest.getHeaders", "getHeaders")
                .in_package("javax.servlet.http")
                .in_class("HttpServletRequest")
                .as_source(),
        );

        registry.register(
            SummarizedCallable::new("javax.servlet.http.HttpServletRequest.getCookies", "getCookies")
                .in_package("javax.servlet.http")
                .in_class("HttpServletRequest")
                .as_source(),
        );

        registry.register(
            SummarizedCallable::new("javax.servlet.http.HttpServletRequest.getParameterValues", "getParameterValues")
                .in_package("javax.servlet.http")
                .in_class("HttpServletRequest")
                .as_source(),
        );

        registry.register(
            SummarizedCallable::new("javax.servlet.http.HttpServletRequest.getParameterNames", "getParameterNames")
                .in_package("javax.servlet.http")
                .in_class("HttpServletRequest")
                .as_source(),
        );

        // SQL sinks
        registry.register(
            SummarizedCallable::new("java.sql.Statement.executeQuery", "executeQuery")
                .in_package("java.sql")
                .in_class("Statement")
                .as_sink("sql"),
        );

        registry.register(
            SummarizedCallable::new("java.sql.Statement.execute", "execute")
                .in_package("java.sql")
                .in_class("Statement")
                .as_sink("sql"),
        );

        registry.register(
            SummarizedCallable::new("java.sql.Statement.executeUpdate", "executeUpdate")
                .in_package("java.sql")
                .in_class("Statement")
                .as_sink("sql"),
        );

        registry.register(
            SummarizedCallable::new("java.sql.Connection.prepareStatement", "prepareStatement")
                .in_package("java.sql")
                .in_class("Connection")
                .as_sink("sql"),
        );

        // Command execution sinks
        registry.register(
            SummarizedCallable::new("java.lang.Runtime.exec", "exec")
                .in_package("java.lang")
                .in_class("Runtime")
                .as_sink("command"),
        );

        registry.register(
            SummarizedCallable::new("java.lang.ProcessBuilder.command", "command")
                .in_package("java.lang")
                .in_class("ProcessBuilder")
                .as_sink("command"),
        );

        registry.register(
            SummarizedCallable::new("java.lang.ProcessBuilder.start", "start")
                .in_package("java.lang")
                .in_class("ProcessBuilder")
                .as_sink("command"),
        );

        // LDAP sinks
        registry.register(
            SummarizedCallable::new("javax.naming.directory.DirContext.search", "search")
                .in_package("javax.naming.directory")
                .in_class("DirContext")
                .as_sink("ldap"),
        );

        // XPath sinks
        registry.register(
            SummarizedCallable::new("javax.xml.xpath.XPath.evaluate", "evaluate")
                .in_package("javax.xml.xpath")
                .in_class("XPath")
                .as_sink("xpath"),
        );

        // HashMap operations
        registry.register(
            SummarizedCallable::new("java.util.HashMap.put", "put")
                .in_package("java.util")
                .in_class("HashMap")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(1), // value argument
                    SummaryComponent::this().with_content(Content::map_value()),
                )),
        );

        registry.register(
            SummarizedCallable::new("java.util.HashMap.get", "get")
                .in_package("java.util")
                .in_class("HashMap")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().with_content(Content::map_value()),
                    SummaryComponent::return_value(),
                )),
        );

        // Collection operations
        registry.register(
            SummarizedCallable::new("java.util.ArrayList.add", "add")
                .in_package("java.util")
                .in_class("ArrayList")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(0),
                    SummaryComponent::this().with_content(Content::collection()),
                )),
        );

        registry.register(
            SummarizedCallable::new("java.util.ArrayList.get", "get")
                .in_package("java.util")
                .in_class("ArrayList")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().with_content(Content::collection()),
                    SummaryComponent::return_value(),
                )),
        );

        // Java Stream API - higher-order functions with callbacks
        // stream.map(fn) - taint flows: this.element -> fn.param[0], fn.return -> result.element
        registry.register(
            SummarizedCallable::new("java.util.stream.Stream.map", "map")
                .in_package("java.util.stream")
                .in_class("Stream")
                // Taint from stream element to callback parameter
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::callback_param(0, 0),
                ))
                // Taint from callback return to result stream element
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::callback_return(0),
                    SummaryComponent::return_value().element(),
                )),
        );

        // stream.filter(fn) - taint flows: this.element -> fn.param[0], this.element -> result.element
        registry.register(
            SummarizedCallable::new("java.util.stream.Stream.filter", "filter")
                .in_package("java.util.stream")
                .in_class("Stream")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::callback_param(0, 0),
                ))
                // Elements pass through unchanged
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::return_value().element(),
                )),
        );

        // stream.forEach(fn) - taint flows: this.element -> fn.param[0]
        registry.register(
            SummarizedCallable::new("java.util.stream.Stream.forEach", "forEach")
                .in_package("java.util.stream")
                .in_class("Stream")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::callback_param(0, 0),
                )),
        );

        // stream.flatMap(fn) - similar to map
        registry.register(
            SummarizedCallable::new("java.util.stream.Stream.flatMap", "flatMap")
                .in_package("java.util.stream")
                .in_class("Stream")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::callback_param(0, 0),
                ))
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::callback_return(0),
                    SummaryComponent::return_value().element(),
                )),
        );

        // stream.reduce(identity, fn) - accumulator pattern
        registry.register(
            SummarizedCallable::new("java.util.stream.Stream.reduce", "reduce")
                .in_package("java.util.stream")
                .in_class("Stream")
                // Initial value flows to result
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(0),
                    SummaryComponent::return_value(),
                ))
                // Element flows to callback
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::callback_param(1, 1),
                ))
                // Callback return flows to result
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::callback_return(1),
                    SummaryComponent::return_value(),
                )),
        );

        // collect - terminal operation, element taint flows to result
        registry.register(
            SummarizedCallable::new("java.util.stream.Stream.collect", "collect")
                .in_package("java.util.stream")
                .in_class("Stream")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::return_value().element(),
                )),
        );

        // findFirst/findAny - element flows to Optional result
        registry.register(
            SummarizedCallable::new("java.util.stream.Stream.findFirst", "findFirst")
                .in_package("java.util.stream")
                .in_class("Stream")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::return_value(),
                )),
        );

        registry.register(
            SummarizedCallable::new("java.util.stream.Stream.findAny", "findAny")
                .in_package("java.util.stream")
                .in_class("Stream")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::return_value(),
                )),
        );

        // Optional.map - similar to Stream.map
        registry.register(
            SummarizedCallable::new("java.util.Optional.map", "map")
                .in_package("java.util")
                .in_class("Optional")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this(),
                    SummaryComponent::callback_param(0, 0),
                ))
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::callback_return(0),
                    SummaryComponent::return_value(),
                )),
        );

        // Optional.orElse - value or default
        registry.register(
            SummarizedCallable::new("java.util.Optional.orElse", "orElse")
                .in_package("java.util")
                .in_class("Optional")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this(),
                    SummaryComponent::return_value(),
                ))
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(0),
                    SummaryComponent::return_value(),
                )),
        );

        registry
    }

    /// Create a registry with JavaScript/TypeScript standard library summaries
    pub fn javascript_stdlib() -> Self {
        let mut registry = Self::new();

        // Array.prototype.map(callback) - taint flows through callback
        registry.register(
            SummarizedCallable::new("Array.prototype.map", "map")
                .in_class("Array")
                // Taint from array element to callback's first parameter
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::callback_param(0, 0),
                ))
                // Taint from callback return to result array element
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::callback_return(0),
                    SummaryComponent::return_value().element(),
                )),
        );

        // Array.prototype.filter(callback) - elements pass through
        registry.register(
            SummarizedCallable::new("Array.prototype.filter", "filter")
                .in_class("Array")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::callback_param(0, 0),
                ))
                // Filtered elements go to result
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::return_value().element(),
                )),
        );

        // Array.prototype.forEach(callback)
        registry.register(
            SummarizedCallable::new("Array.prototype.forEach", "forEach")
                .in_class("Array")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::callback_param(0, 0),
                )),
        );

        // Array.prototype.find(callback) - returns element
        registry.register(
            SummarizedCallable::new("Array.prototype.find", "find")
                .in_class("Array")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::callback_param(0, 0),
                ))
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::return_value(),
                )),
        );

        // Array.prototype.findIndex(callback) - callback receives element
        registry.register(
            SummarizedCallable::new("Array.prototype.findIndex", "findIndex")
                .in_class("Array")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::callback_param(0, 0),
                )),
        );

        // Array.prototype.some/every(callback)
        registry.register(
            SummarizedCallable::new("Array.prototype.some", "some")
                .in_class("Array")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::callback_param(0, 0),
                )),
        );

        registry.register(
            SummarizedCallable::new("Array.prototype.every", "every")
                .in_class("Array")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::callback_param(0, 0),
                )),
        );

        // Array.prototype.reduce(callback, initial)
        registry.register(
            SummarizedCallable::new("Array.prototype.reduce", "reduce")
                .in_class("Array")
                // Initial value flows to result
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(1),
                    SummaryComponent::return_value(),
                ))
                // Element flows to callback's second parameter (currentValue)
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::callback_param(0, 1),
                ))
                // Callback return flows to result
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::callback_return(0),
                    SummaryComponent::return_value(),
                )),
        );

        // Array.prototype.flatMap(callback)
        registry.register(
            SummarizedCallable::new("Array.prototype.flatMap", "flatMap")
                .in_class("Array")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::callback_param(0, 0),
                ))
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::callback_return(0),
                    SummaryComponent::return_value().element(),
                )),
        );

        // Array.prototype.sort(compareFn) - elements pass through
        registry.register(
            SummarizedCallable::new("Array.prototype.sort", "sort")
                .in_class("Array")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this().element(),
                    SummaryComponent::return_value().element(),
                )),
        );

        // Promise.prototype.then(onFulfilled, onRejected)
        registry.register(
            SummarizedCallable::new("Promise.prototype.then", "then")
                .in_class("Promise")
                // Promise value flows to callback's first parameter
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this(),
                    SummaryComponent::callback_param(0, 0),
                ))
                // Callback return flows to returned Promise
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::callback_return(0),
                    SummaryComponent::return_value(),
                )),
        );

        // Promise.prototype.catch(onRejected)
        registry.register(
            SummarizedCallable::new("Promise.prototype.catch", "catch")
                .in_class("Promise")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this(),
                    SummaryComponent::callback_param(0, 0),
                ))
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::callback_return(0),
                    SummaryComponent::return_value(),
                )),
        );

        // Promise.prototype.finally(onFinally)
        registry.register(
            SummarizedCallable::new("Promise.prototype.finally", "finally")
                .in_class("Promise")
                // Value passes through
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this(),
                    SummaryComponent::return_value(),
                )),
        );

        // Promise.all([promises]) - array of promises to promise of array
        registry.register(
            SummarizedCallable::new("Promise.all", "all")
                .in_class("Promise")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(0).element(),
                    SummaryComponent::return_value().element(),
                )),
        );

        // Object.keys/values/entries
        registry.register(
            SummarizedCallable::new("Object.values", "values")
                .in_class("Object")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(0),
                    SummaryComponent::return_value().element(),
                )),
        );

        registry.register(
            SummarizedCallable::new("Object.entries", "entries")
                .in_class("Object")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(0),
                    SummaryComponent::return_value().element(),
                )),
        );

        // String methods
        registry.register(
            SummarizedCallable::new("String.prototype.split", "split")
                .in_class("String")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this(),
                    SummaryComponent::return_value().element(),
                )),
        );

        registry.register(
            SummarizedCallable::new("String.prototype.replace", "replace")
                .in_class("String")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this(),
                    SummaryComponent::return_value(),
                )),
        );

        // JSON.parse - tainted input produces tainted result
        registry.register(
            SummarizedCallable::new("JSON.parse", "parse")
                .in_class("JSON")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(0),
                    SummaryComponent::return_value(),
                )),
        );

        registry
    }

    /// Create a registry with Python standard library summaries
    pub fn python_stdlib() -> Self {
        let mut registry = Self::new();

        // map(fn, iterable) - higher-order function
        registry.register(
            SummarizedCallable::new("builtins.map", "map")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(1).element(),
                    SummaryComponent::callback_param(0, 0),
                ))
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::callback_return(0),
                    SummaryComponent::return_value().element(),
                )),
        );

        // filter(fn, iterable)
        registry.register(
            SummarizedCallable::new("builtins.filter", "filter")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(1).element(),
                    SummaryComponent::callback_param(0, 0),
                ))
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(1).element(),
                    SummaryComponent::return_value().element(),
                )),
        );

        // sorted(iterable, key=fn)
        registry.register(
            SummarizedCallable::new("builtins.sorted", "sorted")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(0).element(),
                    SummaryComponent::return_value().element(),
                )),
        );

        // list comprehension equivalents - list(), tuple()
        registry.register(
            SummarizedCallable::new("builtins.list", "list")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(0).element(),
                    SummaryComponent::return_value().element(),
                )),
        );

        // json.loads - tainted input produces tainted result
        registry.register(
            SummarizedCallable::new("json.loads", "loads")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(0),
                    SummaryComponent::return_value(),
                )),
        );

        // str.join - taint flows from iterable elements
        registry.register(
            SummarizedCallable::new("str.join", "join")
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::argument(0).element(),
                    SummaryComponent::return_value(),
                ))
                .with_propagation(FlowPropagation::taint(
                    SummaryComponent::this(),
                    SummaryComponent::return_value(),
                )),
        );

        registry
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_summary_component_display() {
        assert_eq!(SummaryComponent::argument(0).to_string(), "Argument[0]");
        assert_eq!(SummaryComponent::this().to_string(), "Argument[this]");
        assert_eq!(SummaryComponent::return_value().to_string(), "ReturnValue");
        assert_eq!(
            SummaryComponent::callback_param(0, 0).to_string(),
            "CallbackParam[0, 0]"
        );
        assert_eq!(
            SummaryComponent::callback_return(0).to_string(),
            "CallbackReturn[0]"
        );
    }

    #[test]
    fn test_callback_involves_callback() {
        assert!(SummaryComponent::callback_param(0, 0).involves_callback());
        assert!(SummaryComponent::callback_return(0).involves_callback());
        assert!(!SummaryComponent::argument(0).involves_callback());
        assert!(!SummaryComponent::return_value().involves_callback());

        // Content wrapping callback should still report involves_callback
        let nested = SummaryComponent::callback_return(0).element();
        assert!(nested.involves_callback());
    }

    #[test]
    fn test_summary_component_with_content() {
        let comp = SummaryComponent::argument(0).field("data");
        assert_eq!(comp.to_string(), "Argument[0].Field[data]");
    }

    #[test]
    fn test_flow_propagation() {
        let prop = FlowPropagation::taint(
            SummaryComponent::argument(0),
            SummaryComponent::return_value(),
        );
        assert!(matches!(prop.kind, FlowKind::Taint));
    }

    #[test]
    fn test_summarized_callable() {
        let callable = SummarizedCallable::new("java.lang.String.concat", "concat")
            .in_package("java.lang")
            .in_class("String")
            .with_propagation(FlowPropagation::taint(
                SummaryComponent::argument(0),
                SummaryComponent::return_value(),
            ));

        assert!(callable.matches("concat"));
        assert!(callable.matches("String.concat"));
        assert!(callable.matches("java.lang.String.concat"));
        assert!(!callable.matches("other"));
    }

    #[test]
    fn test_registry_lookup() {
        let registry = FlowSummaryRegistry::java_stdlib();

        let concat = registry.get("concat");
        assert!(concat.is_some());
        assert_eq!(concat.unwrap().name, "concat");

        let escape_html = registry.get("escapeHtml");
        assert!(escape_html.is_some());
        assert!(escape_html.unwrap().is_sanitizer);
    }

    #[test]
    fn test_registry_sources_sinks() {
        let registry = FlowSummaryRegistry::java_stdlib();

        let sources: Vec<_> = registry.sources().collect();
        assert!(!sources.is_empty());
        assert!(sources.iter().any(|s| s.name == "getParameter"));

        let sinks: Vec<_> = registry.sinks().collect();
        assert!(!sinks.is_empty());
        assert!(sinks.iter().any(|s| s.name == "executeQuery"));
    }

    #[test]
    fn test_sanitizer_contexts() {
        let registry = FlowSummaryRegistry::java_stdlib();

        let escape_html = registry.get("escapeHtml").unwrap();
        assert!(escape_html.is_sanitizer);
        assert!(escape_html.sanitizes_for.contains(&"html".to_string()));
        assert!(!escape_html.sanitizes_for.contains(&"sql".to_string()));

        let escape_sql = registry.get("escapeSql").unwrap();
        assert!(escape_sql.is_sanitizer);
        assert!(escape_sql.sanitizes_for.contains(&"sql".to_string()));
        assert!(!escape_sql.sanitizes_for.contains(&"html".to_string()));
    }
}
